### ISSUE TITLE
Fix script is only clearing failed and pending commands

### ISSUE THREAD

**Issue by mrmte** [mannconsulting/JNUC2024#1]
The fix script is only clearing the pending and failed commands. I know it isnt my account because i am manually push it out per machine via the api web interface.

**Comment by isaacatmann** [comment]
Hi @mrmte I just ran a test and the reinstall framework command executed successfully:

```
Recalculating Group Memberships...
{
  "count" : 1
}
Flushing pending MDM commands for Binary Repair...
<?xml version="1.0" encoding="UTF-8"?><commandflush><status>pending+failed</status><computer_groups>[2101]</computer_groups></commandflush>
Reinstalling Framework for Computer ID 18
{
  "deviceId" : "18",
  "commandUuid" : "700543f4-7fba-457f-98f8-15bd65626c42"
}
```

Also when I view the management history for computer 18 I see the InstallApplication command as successful and the Enrollment Date updates.

<img width="1184" alt="Screenshot 2024-10-14 at 8 38 41 AM" src="https://github.com/user-attachments/assets/3d260e41-36ee-4192-8fa3-37fedeb40416">
<img width="458" alt="Screenshot 2024-10-14 at 8 39 01 AM" src="https://github.com/user-attachments/assets/1097eda6-f26d-4794-bde8-f3cd54ae9166">

**Comment by mrmte** [comment]
Yes this only works for one computer and doesn’t work for the rest. All the other machines get their pending and failed commands cleared. So when I went through them manually to reinstall the Jamf framework and then ran the script, only one machine worked.

**Comment by mrmte** [comment]
your command to get the binaryComputers is incorrect. It only returns one.
If i add echo the binaryComputers it only comes back with one machine. ihave tried this with 2 different environments and its the same im afraid.

<img width="374" alt="Screenshot 2024-10-17 at 12 24 45" src="https://github.com/user-attachments/assets/4234ebf7-9a19-4788-9c8b-d92ab3eacbd9">

**Comment by mrmte** [comment]
ah i noticed by error. i was using bash instead of zsh. It is working now
